### PR TITLE
Feature/default vagrant config

### PR DESCRIPTION
**Pull request by svpernova09**
First take on adding a default Vagrantfile with configurable options.

This allows the user to clone this repository, cd into the folder, and run vagrant up. README.md probably needs some clarification on how to use the options.

@rlerdorf If this makes sense to merge in, I'm all for it. If it doesn't make sense that's fine too. This would be a starting point for a box like @auroraeosrose was asking about.

### CODE REVIEW

**Comment by svpernova09** [comment]
There should definitely be something about checking out the local repo. There is likely some other clarification that the docs need.

Yes, hard coding the IP so we can be sure it won't change. This _shouldn't_ cause an issue unless the user's network is using 192.7.7.x.

**Comment by svpernova09** [comment]
DHCP VS Static: My personal preference is to know where the box is so I can add it to the hosts file & use 3rd party tools such as MySQL Workbench with a saved config. This way I'm not always having to check ifconfig and update other apps.

I'm fine with removing the port forwards until if/when they're deemed necessary.

**Comment by rlerdorf** [comment]
My problem with the static hardcoded 192.7 ip is that you can't be sure it is reachable from other machines on the network. The netmask might not be set to allow it or the local network could be a 172.x/10.x. I never actually run my VMs on the same machine I access them from here, if we are trying to make this a flexible setup mechanism there should at least be an option for the user to choose. Or try to be smart and look at the host ip and netmask or something awful like that. Also, 192.7 is not actually a private network. It is a fully routable public network. It would need to be 192.168.7.7.

**Comment by svpernova09** [comment]
Gotcha,

I'll tweak the private IP to be 192.168.7.7 and add an option to enable a public DHCP interface

**Comment by svpernova09** [comment]
So in `scripts/serve.sh` we should change `try_files \$uri \$uri/ /index.php?\$query_string;` to `try_files $uri =404;`?

I believe I'm understanding correctly.

**Comment by rlerdorf** [comment]
Yeah, but I am having trouble following what this actually solves to begin with. It is so you can configure a new vhost from outside the box? What would the workflow be?

**Comment by svpernova09** [comment]
Yes, the idea is that you would add vhosts to the box by adding them to the php7dev.yaml file in the sites section.

You would add a folder to the box in the folders section and then a site to the sites section.

The default option in there now is this:

```
folders:
    - map: scripts
      to: /home/vagrant/scripts
...
sites:
    - map: php7dev.dev
      to: /home/vagrant/scripts
```

Obviously this won't work because we're mapping our own scripts folder to the domain.

The goal would be something like this:

```
folders:
    - map:  ~/path/to/phpbb
      to: /var/www/phpbb
...
sites:
    - map: phpbb.dev
      to: /var/www/phpbb
```

**Comment by svpernova09** [comment]
I'm quickly coming to the realization that the needed level of customization for the vhost configuration may not be worthwhile. I'd be fine scrapping that functionality and having that just be up to the end user.

**Comment by rlerdorf** [comment]
Yes, it is pretty much impossible to come up with a generic nginx config that will work for everything. The best you can do is a very generic default template that you then add individual rewrite rules to. Some examples:
http://wiki.nginx.org/MediaWiki
http://wiki.nginx.org/Drupal
http://wiki.nginx.org/Wordpress (scroll down to see all the various options)

Still trying to understand what putting the site definition in a yaml file buys us as opposed to putting it directly in /etc/nginx/conf.d on the box? Is it to survive box updates? Or is it a provisioning thing so you can quickly spin up a fully-baked Wordpress machine, for example?

**Comment by svpernova09** [comment]
It's the flexibility of spinning up sites easier VS having to ssh into the box to configure. But with trying to support so many different variations we would either need to come up with some generic types (phpbb, wordpress, drupal, etc) and have that as an option in the config. I'm fine with that if there's useful value. Otherwise I'm going to strip out the site config parts.

**Comment by rlerdorf** [comment]
Yeah, I don't think we should try to solve the nginx config problem. It would actually be a really cool service for someone to maintain. A database of nginx configs with perhaps a customization ui/api so you could specify that you wanted a. "single-site Wordpress hosted in a sub-directory of /var/www/my_site" and it would generate and return the config. If such a service existed we could make a call to that, but building it is a bit beyond the scope here.

**Comment by svpernova09** [comment]
I've removed the vhost configuration stuff, and added a bit of documentation about adding shared folders, databases, and how to toggle the public network interface.

**Comment by rlerdorf** [comment]
By the way, with all this extra automation, we have lost Windows support, haven't we? We should probably have some manual instructions for Windows users.

**Comment by svpernova09** [comment]
I'll test this out in Windows and add any Windows specific notes needed to the readme.

**Comment by svpernova09** [comment]
Tested on Windows 7 (Patched and up to date), Vagrant 1.6.5 and everything worked as expected.

**Pull request merged**
